version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HF_USERNAME: ${HF_USERNAME}
        HF_TOKEN: ${HF_TOKEN}
    gpus: all
    volumes:
      - ..:/workspace:cached
    ports:
      - "8077:8000"
    command: sleep infinity
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility