# name: Move PR back to Review on new commits

# on:
#   push:
#     branches-ignore:
#       - main
#       - master

# jobs:
#   move-back:
#     runs-on: ubuntu-latest
#     if: github.event.pusher.name != 'github-actions[bot]'
#     steps:
#       - name: Get associated PR
#         id: pr
#         uses: 8BitJonny/gh-get-associated-pull-request@v3
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Move PR to Review
#         if: steps.pr.outputs.number != ''
#         uses: peter-evans/update-project-item@v2
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           project-url: https://github.com/users/Yoshiki0418/projects/8
#           item-type: pull-request
#           item-number: ${{ steps.pr.outputs.number }}
#           field: Status
#           value: Review
